In [5]:
import numpy as np

n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [7]:
n2 = np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [9]:
type(n2)

numpy.ndarray

In [10]:
import numpy as np
n1 = np.zeros((1,2))
n1

array([[0., 0.]])

In [12]:
import numpy as np
n1 = np.zeros((5,5))
n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
import numpy as np
n1 = np.zeros((10,2))
n1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
import numpy as np
n1 = np.zeros((10,1))
n1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
import numpy as np
n1 = np.full((2,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10]])

In [23]:
import numpy as np
n1 = np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
n2 = np.arange(10,50,2)
n2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [28]:
n1 = np.arange(50,101)
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
n1 = np.arange(50,500,10)
n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [35]:
import numpy as np
n1 = np.random.randint(1,100,10)
n1

array([39, 82,  8, 12, 63, 52, 87, 64, 57, 48])

In [45]:
import numpy as np
n1 = np.array([[1,2,3],[4,5,6]])
print(n1.shape)
print(n1)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [47]:
n1.shape = (3,2)
n1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
n1.shape = (6,1)
n1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
import numpy as np
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
import numpy as np
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [52]:
import numpy as np
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
import numpy as np
n1 = np.array([1,2,3,4,5,6,7,8,9])
n2 = np.array([4,5,6])

np.intersect1d(n1,n2)

array([4, 5, 6])

In [57]:
import numpy as np
n1 = np.array([1,2,3,4,5,6,7,8,9])
n2 = np.array([4,5,6])

np.setdiff1d(n1,n2)

array([1, 2, 3, 7, 8, 9])

In [58]:
import numpy as np
n1 = np.array([1,2,3,4,5,6,7,8,9])
n2 = np.array([4,5,6])

np.setdiff1d(n2,n1)

array([], dtype=int32)

In [59]:
import numpy as np
n1 = np.array([10,20])
n2 = np.array([30,40])

np.sum((n1,n2))

100

In [60]:
np.sum([n1,n2],axis = 0)

array([40, 60])

In [61]:
np.sum([n1,n2],axis = 1)

array([30, 70])

# Basic mathematical operations

In [62]:
import numpy as np
n1 = np.array([10,20,30])

n1 = n1+1
n1

array([11, 21, 31])

In [63]:
import numpy as np
n1 = np.array([10,20,30])

n1 = n1*2
n1

array([20, 40, 60])

In [64]:
import numpy as np
n1 = np.array([10,20,30])

n1 = n1-1
n1

array([ 9, 19, 29])

In [66]:
import numpy as np
n1 = np.array([10,20,30])

n1 = n1/5
n1

array([2., 4., 6.])

# Mean,Median and std

In [67]:
import numpy as np
n1 = np.array([10,20,30,40])

np.mean(n1)

25.0

In [68]:
import numpy as np
n1 = np.array([10,20,30,40])

np.median(n1)

25.0

In [69]:
import numpy as np
n1 = np.array([10,20,30,40])

np.std(n1)

11.180339887498949

# Save and load

In [72]:
import numpy as np
n1 = np.array([10,20,30,40,50])
np.save('my_numpy',n1)


In [74]:
n2 = np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50])